---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
data("diamonds")
```
1. Lấy các cột price, cut, color và clarity
```{r}
diamonds_sub <- diamonds[, c("price", "cut", "color", "clarity")]
diamonds_sub
```

2. Phân tích ANOVA 1 nhân tố

```{r}
anova_one_factor <- function(response, factor, data) {
  model <- aov(as.formula(paste(response, "~", factor)), data = data)
  print(summary(model))
  return(model)
}
```

```{r}
anova_cut <- anova_one_factor("price", "cut", diamonds_sub)
anova_color <- anova_one_factor("price", "color", diamonds_sub)
anova_clarity <- anova_one_factor("price", "clarity", diamonds_sub)
```
3. Phân tích ANOVA 2 nhân tố
- Chọn 2 yếu tố, ví dụ cut và color
```{r}
anova_two_factors <- aov(price ~ cut * color, data = diamonds_sub)
summary(anova_two_factors)
```
- Phân loại các nhóm theo trung bình

```{r}
library(agricolae)
tukey_cut_color <- HSD.test(anova_two_factors, trt = "cut", group = TRUE)
print(tukey_cut_color)
```
- Kiểm tra các giả thiết của mô hình
```{r}
par(mfrow = c(2, 2))
plot(anova_two_factors)
```


```{r}
leveneTest(price ~ cut * color, data = diamonds_sub)
```



```{r}
hist(diamonds_sub$price, breaks = 30, main = "Histogram of Price", xlab = "Price")
```

```{r}
diamonds_sub$log_price <- log(diamonds_sub$price)
hist(diamonds_sub$log_price, breaks = 30, main = "Histogram of Log(Price)", xlab = "Log(Price)")
```

```{r}
anova_log <- aov(log_price ~ cut * color, data = diamonds_sub)
summary(anova_log)
par(mfrow = c(2, 2))
plot(anova_log)
leveneTest(log_price ~ cut * color, data = diamonds_sub)
```

















