
	SUBROUTINE GAGM_CONFIG(KPOC)
	IMPLICIT DOUBLE PRECISION (A-H,O-Z)
	PARAMETER (MXHAT=100,MXMOL=1000)
	CHARACTER*3 HAMN,HATN,SATN
	COMMON /HETATM/ NMOL,HAMN(MXMOL),IAM(MXMOL),
	*                HAFX(MXMOL),HAFY(MXMOL),HAFZ(MXMOL),
	*                HATN(MXMOL,MXHAT),HATX(MXMOL,MXHAT),
     *                HATY(MXMOL,MXHAT),HATZ(MXMOL,MXHAT)
	COMMON /SUBSTANCE/ NSA,SATFX,SATFY,SATFZ,SATN(MXHAT),
	*                   SATX(MXHAT),SATY(MXHAT),SATZ(MXHAT)
	COMMON /RMSCOORD/  RATX(MXHAT),RATY(MXHAT),RATZ(MXHAT)
	PARAMETER (NPARMAX=7)
	COMMON /COEFFICIENT/ CET(NPARMAX)
	COMMON /INPPOCKET/ NPARTX,NPARTY,NPARTZ,DISMIN,DISMAX,PVLIM,PSPACE
	COMMON /POCKET/ NPK,PKX(1000),PKY(1000),PKZ(1000),PVL(1000)

c    $$$$$$$$$$-Define Place-$$$$$$$$$$
	
	DELR=DISMIN
	X0=PKX(KPOC)+(CET(1)-0.5)*DELR
	Y0=PKY(KPOC)+(CET(2)-0.5)*DELR
	Z0=PKZ(KPOC)+(CET(3)-0.5)*DELR

      A=180*CET(4)/2.D0
      B=180*CET(5)
      C=180*CET(6)
	DO I=1,IAM(1)
	 RATX(I)=SATX(I)
	 RATY(I)=SATY(I)
	 RATZ(I)=SATZ(I)
	 CALL ROTATE(A,B,C,RATX(I),RATY(I),RATZ(I))
	 CALL ADVANCE(X0,Y0,Z0,RATX(I),RATY(I),RATZ(I))
	END DO

	RETURN
	END

	SUBROUTINE GAGM_LASTCONFIG(j)
	IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      parameter (indmax=200,nchrmax=180,nparmax=7)
      dimension parent(nparmax,indmax),iparent(nchrmax,indmax)
      common / ga3   / parent,iparent

	COMMON /GARUN/ MSTATUS,NSTATUS
	COMMON /GAFUN/ NFV,BFUNC(100)	       
	CHARACTER*20 DINP,DOUT
	COMMON /DIRGA/ DINP,DOUT,LCINP,LCOUT
	COMMON /COEFFICIENT/ CET(NPARMAX)

	PARAMETER (MXHAT=100,MXMOL=1000)
	CHARACTER*3 HAMN,HATN,SATN
	COMMON /HETATM/ NMOL,HAMN(MXMOL),IAM(MXMOL),
	*                HAFX(MXMOL),HAFY(MXMOL),HAFZ(MXMOL),
	*                HATN(MXMOL,MXHAT),HATX(MXMOL,MXHAT),
     *                HATY(MXMOL,MXHAT),HATZ(MXMOL,MXHAT)
	COMMON /SUBSTANCE/ NSA,SATFX,SATFY,SATFZ,SATN(MXHAT),
	*                   SATX(MXHAT),SATY(MXHAT),SATZ(MXHAT)
	COMMON /RMSCOORD/  RATX(MXHAT),RATY(MXHAT),RATZ(MXHAT)

	do i=1,7 
       CET(i)=parent(i,j)
	end do
	CALL GAGM_CONFIG(NSTATUS)

	if (NSTATUS.EQ.1) then 
	open(unit=28,file=DOUT(:LCOUT)//'configuration.out',
	*     STATUS='UNKNOWN')
	else
	open(unit=28,file=DOUT(:LCOUT)//'configuration.out',
	*     STATUS='UNKNOWN',ACCESS='APPEND')
	endif
	 write(28,*) '   THE LAST CONFIGURATION FOR POCKET ',NFV
	 do i=1,IAM(1)
	  write(28,'(A1,3F16.4)') SATN(i),RATX(i),RATY(i),RATZ(i) 
	 end do
	 write(28,*)
	close(28)
ct	CALL RMS_SUBSTANCE(RMS)
ct	write(*,*) RMS

	RETURN
	END

	SUBROUTINE GAGM_ANALYST(TARV)
	IMPLICIT DOUBLE PRECISION (A-H,O-Z)
	PARAMETER (MXPR=100000,MXAA=1000,MXCH=10)
	CHARACTER CHN*1,AAN*3,PRN*3
      COMMON /PROTEIN/ CHN(MXCH),
	*                 AAN(MXCH,MXAA),IAS(MXCH,MXAA),IAE(MXCH,MXAA),
	*                 AAFX(MXCH,MXAA),AAFY(MXCH,MXAA),AAFZ(MXCH,MXAA),
	*                 PRN(MXPR),PRX(MXPR),PRY(MXPR),PRZ(MXPR),
	*                 IFOCH,IFOAA(MXCH)
	PARAMETER (MXHAT=100,MXMOL=1000)
	CHARACTER*3 HAMN,HATN,SATN
	COMMON /HETATM/ NMOL,HAMN(MXMOL),IAM(MXMOL),
	*                HAFX(MXMOL),HAFY(MXMOL),HAFZ(MXMOL),
	*                HATN(MXMOL,MXHAT),HATX(MXMOL,MXHAT),
     *                HATY(MXMOL,MXHAT),HATZ(MXMOL,MXHAT)
	COMMON /SUBSTANCE/ NSA,SATFX,SATFY,SATFZ,SATN(MXHAT),
	*                   SATX(MXHAT),SATY(MXHAT),SATZ(MXHAT)
	COMMON /RMSCOORD/  RATX(MXHAT),RATY(MXHAT),RATZ(MXHAT)

c    $$$$$$$$$$-Define RMS-$$$$$$$$$$
	
	CALL RMS_SUBSTANCE(RMS)

c    $$$$$$$$$$-Define Target Value-$$$$$$$$$$
	
	R2MIN=(PRX(1)-RATX(1))**2+(PRY(1)-RATY(1))**2
	*     +(PRZ(1)-RATZ(1))**2
	write(*,'(F23.15)') RMS
	DO I=1,IAM(1)
	 DO J=1,IAE(IFOCH,IFOAA(IFOCH))
	  DX = PRX(J) - RATX(I)
	  DY = PRY(J) - RATY(I)
	  DZ = PRZ(J) - RATZ(I)
	  DR2 = DX*DX+DY*DY+DZ*DZ
	  IF (DR2.LT.R2MIN) THEN
	   R2MIN= DR2
	  ENDIF
	 END DO
	END DO

	TARV=DSQRT(R2MIN)

	RETURN
	END