
	SUBROUTINE MM_COEFFICIENT
	IMPLICIT DOUBLE PRECISION (A-H,O-Z)
	CHARACTER*8 PRFN,SUBFN
	COMMON /INPUT/ PRFN,SUBFN

	 CALL PRO_MM
	 CALL HDR_MM
	 CALL SUB_MM

	RETURN
	END

	SUBROUTINE PRO_MM
	IMPLICIT DOUBLE PRECISION (A-H,O-Z)
	CHARACTER LINE*100
	PARAMETER (MXPR=100000,MXAA=1000,MXCH=10)
	CHARACTER CHN*1,AAN*3,PRN*3
      COMMON /PROTEIN/ CHN(MXCH),
	*                 AAN(MXCH,MXAA),IAS(MXCH,MXAA),IAE(MXCH,MXAA),
	*                 AAFX(MXCH,MXAA),AAFY(MXCH,MXAA),AAFZ(MXCH,MXAA),
	*                 PRN(MXPR),PRX(MXPR),PRY(MXPR),PRZ(MXPR),
	*                 IFOCH,IFOAA(MXCH)
      COMMON /MMPROTE/ PRQ(MXPR),PRS(MXPR),PRE(MXPR)

	DO I=1,IFOCH

	 J=1
	 OPEN(UNIT=21,FILE='Data/'//AAN(I,J)//'.dat')
	 OPEN(UNIT=22,FILE='Data/TER.dat')
	  READ(21,*)
	  READ(22,'(A100)') LINE
	  K=IAS(I,J)
	  READ(LINE(27:55),*) PRQ(K),PRS(K),PRE(K)
	  DO K=IAS(I,J)+1,IAE(I,J)
	   READ(21,'(A100)') LINE
	   READ(LINE(27:55),*) PRQ(K),PRS(K),PRE(K)
	  END DO
	 CLOSE(21)
	 CLOSE(22)

	 DO J=2,IFOAA(I)-1
	  OPEN(UNIT=21,FILE='Data/'//AAN(I,J)//'.dat')
	   DO K=IAS(I,J),IAE(I,J)
	    READ(21,'(A100)') LINE
	    READ(LINE(27:55),*) PRQ(K),PRS(K),PRE(K)
	   END DO
	  CLOSE(21)
	 END DO

	 J=IFOAA(I)
	 OPEN(UNIT=21,FILE='Data/'//AAN(I,J)//'.dat')
	 OPEN(UNIT=22,FILE='Data/TER.dat')
	  DO K=IAS(I,J),IAE(I,J)-1
	   READ(21,'(A100)') LINE
	   READ(LINE(27:55),*) PRQ(K),PRS(K),PRE(K)
	  END DO
	  K=IAE(I,J)
	  IF (PRN(K).EQ.'OXT') THEN
	   READ(22,*)
	   READ(22,'(A100)') LINE
	   READ(LINE(27:55),*) PRQ(K),PRS(K),PRE(K)
	  ELSE
	   READ(21,'(A100)') LINE
	   READ(LINE(27:55),*) PRQ(K),PRS(K),PRE(K)	 
	  ENDIF
	 CLOSE(21)
	 CLOSE(22)

	END DO

	RETURN
	END

	SUBROUTINE HDR_MM
	IMPLICIT DOUBLE PRECISION (A-H,O-Z)
	CHARACTER LINE*100
	PARAMETER (MXPR=100000,MXAA=1000,MXCH=10)
	CHARACTER CHN*1,AAN*3,PRN*3
      COMMON /PROTEIN/ CHN(MXCH),
	*                 AAN(MXCH,MXAA),IAS(MXCH,MXAA),IAE(MXCH,MXAA),
	*                 AAFX(MXCH,MXAA),AAFY(MXCH,MXAA),AAFZ(MXCH,MXAA),
	*                 PRN(MXPR),PRX(MXPR),PRY(MXPR),PRZ(MXPR),
	*                 IFOCH,IFOAA(MXCH)
	COMMON /HIDROPR/ IHS(MXCH,MXAA),IHE(MXCH,MXAA),
	*                 HPX(MXPR),HPY(MXPR),HPZ(MXPR)
      COMMON /MMHIDRO/ HPQ(MXPR),HPS(MXPR),HPE(MXPR)

	DO I=1,IFOCH

	 J=1
	 OPEN(UNIT=21,FILE='Data/'//AAN(I,J)//'.dat')
	 OPEN(UNIT=22,FILE='Data/TER.dat')
	  READ(22,*)
	  READ(22,*)
	  READ(22,'(A100)') LINE
	  IF (AAN(I,J).EQ.'PRO') THEN
	   NS=IAS(I,J)
	   NE=NS+1
	   DO K=NS,NE
	    READ(LINE(27:55),*) HPQ(K),HPS(K),HPE(K)
	   END DO
	   DO
	    READ(21,'(A100)',ERR=100) LINE
	    IF (LINE(60:60).EQ.'h') THEN
	     READ(LINE(1:1),*) ND
	     NE=NE+ND
	     DO K=NS,NE
	      READ(LINE(27:55),*) HPQ(K),HPS(K),HPE(K)
	     END DO
	     NS=NE+1
	    ENDIF
	   END DO
	  ELSE
	   NS=IAS(I,J)
	   NE=NS+2
	   NT=0
	   DO K=NS,NE
	    READ(LINE(27:55),*) HPQ(K),HPS(K),HPE(K)
	   END DO
	   DO
	    READ(21,'(A100)',ERR=100) LINE
	    IF ((LINE(60:60).EQ.'h').AND.(LINE(1:3).NE.'1H ')) THEN
	     READ(LINE(1:1),*) ND
	     NE=NE+ND
	     DO K=NS,NE
	      READ(LINE(27:55),*) HPQ(K),HPS(K),HPE(K)
	     END DO
	     NS=NE+1
	    ENDIF
	   END DO
	  ENDIF 
100	 CLOSE(21)
	 CLOSE(22)

	 DO J=2,IFOAA(I)
	  OPEN(UNIT=21,FILE='Data/'//AAN(I,J)//'.dat')
	    NS=IAS(I,J)
	    NE=NS-1
	   DO
	    READ(21,'(A100)',ERR=110) LINE
	    IF (LINE(60:60).EQ.'h') THEN
	     READ(LINE(1:1),*) ND
	     NE=NE+ND
	     DO K=NS,NE
	      READ(LINE(27:55),*) HPQ(K),HPS(K),HPE(K)
	     END DO
	     NS=NE+1
	    ENDIF
	   END DO
110	  CLOSE(21)
	 END DO

	END DO


	RETURN
	END

	SUBROUTINE SUB_MM
	IMPLICIT DOUBLE PRECISION (A-H,O-Z)
	CHARACTER LINE*100
	CHARACTER*8 PRFN,SUBFN
	COMMON /INPUT/ PRFN,SUBFN
	PARAMETER (MXHAT=100)
	CHARACTER*3 SATN
	COMMON /SUBSTANCE/ NSA,SATFX,SATFY,SATFZ,SATN(MXHAT),
	*                   SATX(MXHAT),SATY(MXHAT),SATZ(MXHAT)
      COMMON /MMSUBSTAN/ SAQ(MXHAT),SAS(MXHAT),SAE(MXHAT)

	IF (SUBFN.NE.'        ') THEN

	 OPEN(UNIT=12, FILE='PDB_File/'//SUBFN, STATUS='UNKNOWN')
	  READ(12,*)
	  READ(12,*)
	  DO I=1,NSA
	   READ(12,'(A100)') LINE
	   READ(LINE(31:57),*) SAQ(I),SAS(I),SAE(I)
	  END DO
	 CLOSE(12)

	ENDIF

	RETURN
	END

	SUBROUTINE LJ612(ELJ)
	IMPLICIT DOUBLE PRECISION (A-H,O-Z)
	PARAMETER (MXPR=100000,MXAA=1000,MXCH=10,MXHAT=100)
	CHARACTER CHN*1,AAN*3,PRN*3
      COMMON /PROTEIN/ CHN(MXCH),
	*                 AAN(MXCH,MXAA),IAS(MXCH,MXAA),IAE(MXCH,MXAA),
	*                 AAFX(MXCH,MXAA),AAFY(MXCH,MXAA),AAFZ(MXCH,MXAA),
	*                 PRN(MXPR),PRX(MXPR),PRY(MXPR),PRZ(MXPR),
	*                 IFOCH,IFOAA(MXCH)
      COMMON /MMPROTE/ PRQ(MXPR),PRS(MXPR),PRE(MXPR)
	COMMON /HIDROPR/ IHS(MXCH,MXAA),IHE(MXCH,MXAA),
	*                 HPX(MXPR),HPY(MXPR),HPZ(MXPR)
      COMMON /MMHIDRO/ HPQ(MXPR),HPS(MXPR),HPE(MXPR)
	CHARACTER*3 SATN
	COMMON /SUBSTANCE/ NSA,SATFX,SATFY,SATFZ,SATN(MXHAT),
	*                   SATX(MXHAT),SATY(MXHAT),SATZ(MXHAT)
	COMMON /RMSCOORD/  RATX(MXHAT),RATY(MXHAT),RATZ(MXHAT)
      COMMON /MMSUBSTAN/ SAQ(MXHAT),SAS(MXHAT),SAE(MXHAT)

	   TOTENERGLJ=0					  
	   DO I=1,IAE(IFOCH,IFOAA(IFOCH))
	    DO J=1,NSA
	     SIGMA=(SAS(J)+PRS(I))/2
	     EPSIL=DSQRT(SAE(J)*PRE(I))
	     DLength=DSQRT((RATX(J)-PRX(I))**2+
	*	               (RATY(J)-PRY(I))**2+
     *                   (RATZ(J)-PRZ(I))**2)
	     IF (DLength.LT.1D-2) THEN
	      DLength=1D-2
	     ENDIF
	     SR6=(SIGMA/DLength)**6
	     ENERGLJ=4*EPSIL*(SR6**2-SR6)
		 TOTENERGLJ=TOTENERGLJ+ENERGLJ
	    END DO
	   END DO

	   DO I=1,IHE(IFOCH,IFOAA(IFOCH))
	    DO J=1,NSA
	     SIGMA=(SAS(J)+HPS(I))/2
	     EPSIL=DSQRT(SAE(J)*HPE(I))
	     DLength=DSQRT((RATX(J)-HPX(I))**2+
	*	               (RATY(J)-HPY(I))**2+
     *                   (RATZ(J)-HPZ(I))**2)
	     IF (DLength.LT.1D-2) THEN
	      DLength=1D-2
	     ENDIF
	     SR6=(SIGMA/DLength)**6
	     ENERGLJ=4*EPSIL*(SR6**2-SR6)
		 TOTENERGLJ=TOTENERGLJ+ENERGLJ
	    END DO
	   END DO

	   ELJ=TOTENERGLJ

	RETURN
	END

	SUBROUTINE GAMM_ANALYST(TARV)
	IMPLICIT DOUBLE PRECISION (A-H,O-Z)
	PARAMETER (MXPR=100000,MXAA=1000,MXCH=10)
	CHARACTER CHN*1,AAN*3,PRN*3
      COMMON /PROTEIN/ CHN(MXCH),
	*                 AAN(MXCH,MXAA),IAS(MXCH,MXAA),IAE(MXCH,MXAA),
	*                 AAFX(MXCH,MXAA),AAFY(MXCH,MXAA),AAFZ(MXCH,MXAA),
	*                 PRN(MXPR),PRX(MXPR),PRY(MXPR),PRZ(MXPR),
	*                 IFOCH,IFOAA(MXCH)
	PARAMETER (MXHAT=100,MXMOL=1000)
	CHARACTER*3 HAMN,HATN,SATN
	COMMON /HETATM/ NMOL,HAMN(MXMOL),IAM(MXMOL),
	*                HAFX(MXMOL),HAFY(MXMOL),HAFZ(MXMOL),
	*                HATN(MXMOL,MXHAT),HATX(MXMOL,MXHAT),
     *                HATY(MXMOL,MXHAT),HATZ(MXMOL,MXHAT)
	COMMON /SUBSTANCE/ NSA,SATFX,SATFY,SATFZ,SATN(MXHAT),
	*                   SATX(MXHAT),SATY(MXHAT),SATZ(MXHAT)
	COMMON /RMSCOORD/  RATX(MXHAT),RATY(MXHAT),RATZ(MXHAT)

c    $$$$$$$$$$-Define RMS-$$$$$$$$$$
	
	CALL RMS_SUBSTANCE(RMS)

c    $$$$$$$$$$-Define Target Value-$$$$$$$$$$
	
	write(*,'(F23.15)') RMS
	CALL LJ612(TARV) 

	RETURN
	END

	SUBROUTINE GAMM_CONFIG(KPOC)
	IMPLICIT DOUBLE PRECISION (A-H,O-Z)
	PARAMETER (MXHAT=100,MXMOL=1000)
	CHARACTER*3 HAMN,HATN,SATN
	COMMON /HETATM/ NMOL,HAMN(MXMOL),IAM(MXMOL),
	*                HAFX(MXMOL),HAFY(MXMOL),HAFZ(MXMOL),
	*                HATN(MXMOL,MXHAT),HATX(MXMOL,MXHAT),
     *                HATY(MXMOL,MXHAT),HATZ(MXMOL,MXHAT)
	COMMON /SUBSTANCE/ NSA,SATFX,SATFY,SATFZ,SATN(MXHAT),
	*                   SATX(MXHAT),SATY(MXHAT),SATZ(MXHAT)
	COMMON /RMSCOORD/  RATX(MXHAT),RATY(MXHAT),RATZ(MXHAT)
	PARAMETER (NPARMAX=7)
	COMMON /COEFFICIENT/ CET(NPARMAX)
	COMMON /INPPOCKET/ NPARTX,NPARTY,NPARTZ,DISMIN,DISMAX,PVLIM,PSPACE
	COMMON /POCKET/ NPK,PKX(1000),PKY(1000),PKZ(1000),PVL(1000)

c    $$$$$$$$$$-Define Place-$$$$$$$$$$
	
	DELR=DISMIN
	X0=PKX(KPOC)+(CET(1)-0.5)*DELR
	Y0=PKY(KPOC)+(CET(2)-0.5)*DELR
	Z0=PKZ(KPOC)+(CET(3)-0.5)*DELR

      A=180*CET(4)/2.D0
      B=180*CET(5)
      C=180*CET(6)
	DO I=1,NSA
	 RATX(I)=SATX(I)
	 RATY(I)=SATY(I)
	 RATZ(I)=SATZ(I)
	 CALL ROTATE(A,B,C,RATX(I),RATY(I),RATZ(I))
	 CALL ADVANCE(X0,Y0,Z0,RATX(I),RATY(I),RATZ(I))
	END DO

	RETURN
	END

	SUBROUTINE GAMM_LASTCONFIG(j)
	IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      parameter (indmax=200,nchrmax=180,nparmax=7)
      dimension parent(nparmax,indmax),iparent(nchrmax,indmax)
      common / ga3   / parent,iparent

	COMMON /GARUN/ MSTATUS,NSTATUS	       
	COMMON /COEFFICIENT/ CET(NPARMAX)

	PARAMETER (MXHAT=100,MXMOL=1000)
	CHARACTER*3 HAMN,HATN,SATN
	COMMON /HETATM/ NMOL,HAMN(MXMOL),IAM(MXMOL),
	*                HAFX(MXMOL),HAFY(MXMOL),HAFZ(MXMOL),
	*                HATN(MXMOL,MXHAT),HATX(MXMOL,MXHAT),
     *                HATY(MXMOL,MXHAT),HATZ(MXMOL,MXHAT)
	COMMON /SUBSTANCE/ NSA,SATFX,SATFY,SATFZ,SATN(MXHAT),
	*                   SATX(MXHAT),SATY(MXHAT),SATZ(MXHAT)
	COMMON /RMSCOORD/  RATX(MXHAT),RATY(MXHAT),RATZ(MXHAT)

	do i=1,7 
       CET(i)=parent(i,j)
	end do
	CALL GAMM_CONFIG(NSTATUS)
 
	OPEN(UNIT=21,FILE='GAMM/HETA.pdb')
	 N=0
	 L=1
	 DO I=1,NSA
	  N=N+1
	  write(21,'(A6,I5,A5,A4,A2,I4,A4,3F8.3)')
	+   'HETATM',N,SATN(I),HAMN(1),'  ',L,'    ',
	+   RATX(I),RATY(I),RATZ(I)
	 END DO
	CLOSE(21)
	CALL RMS_SUBSTANCE(RMS)
	write(*,'(E18.4)') RMS

	RETURN
	END