
	SUBROUTINE PROTEIN_ANALYSE
	IMPLICIT DOUBLE PRECISION (A-H,O-Z)

	CALL S_BRIDGE

	RETURN
	END

	SUBROUTINE S_BRIDGE
	IMPLICIT DOUBLE PRECISION (A-H,O-Z)
	PARAMETER (MXPR=100000,MXAA=1000,MXCH=10)
	CHARACTER CHN*1,AAN*3,PRN*3
      COMMON /PROTEIN/ CHN(MXCH),
	*                 AAN(MXCH,MXAA),IAS(MXCH,MXAA),IAE(MXCH,MXAA),
	*                 AAFX(MXCH,MXAA),AAFY(MXCH,MXAA),AAFZ(MXCH,MXAA),
	*                 PRN(MXPR),PRX(MXPR),PRY(MXPR),PRZ(MXPR),
	*                 IFOCH,IFOAA(MXCH)
	DIMENSION IC(MXAA),IA(MXAA)
	COMMON /SBRIDGE/ NBR,ICB(MXAA),IAB(MXAA),JCB(MXAA),JAB(MXAA)

	NCYS=0
	DO I=1,IFOCH
	 DO J=1,IFOAA(I)
	  IF (AAN(I,J).EQ.'CYS') THEN
	   NCYS=NCYS+1
	   IC(NCYS)=I
	   IA(NCYS)=J
	  ENDIF
	 END DO
	END DO 

	NBR=0
	DO I=1,NCYS
	 DO J=1,NCYS
	  IF (J.NE.I) THEN
	   SBX=(PRX(IAS(IC(I),IA(I))+5)-PRX(IAS(IC(J),IA(J))+5))**2
	   SBY=(PRY(IAS(IC(I),IA(I))+5)-PRY(IAS(IC(J),IA(J))+5))**2
	   SBZ=(PRZ(IAS(IC(I),IA(I))+5)-PRZ(IAS(IC(J),IA(J))+5))**2
	   SBD=DSQRT(SBX+SBY+SBZ)
	   IF (SBD.LT.2.5) THEN
	    NBR=NBR+1
	    ICB(NBR)=IC(I)
	    IAB(NBR)=IA(I)
	    JCB(NBR)=IC(J)
	    JAB(NBR)=IA(J)		 
	   ENDIF
	  ENDIF
	 END DO
	END DO

	RETURN
	END