	
	SUBROUTINE RMS_SUBSTANCE(RMS)
	IMPLICIT DOUBLE PRECISION (A-H,O-Z)
	PARAMETER (MXHAT=100,MXMOL=1000)
	CHARACTER*3 HAMN,HATN,SATN
	COMMON /HETATM/ NMOL,HAMN(MXMOL),IAM(MXMOL),
	*                HAFX(MXMOL),HAFY(MXMOL),HAFZ(MXMOL),
	*                HATN(MXMOL,MXHAT),HATX(MXMOL,MXHAT),
     *                HATY(MXMOL,MXHAT),HATZ(MXMOL,MXHAT)
	COMMON /SUBSTANCE/ NSA,SATFX,SATFY,SATFZ,SATN(MXHAT),
	*                   SATX(MXHAT),SATY(MXHAT),SATZ(MXHAT)
	COMMON /RMSCOORD/  RATX(MXHAT),RATY(MXHAT),RATZ(MXHAT)

	SM=0
	DO I=1,IAM(1)
	 SM=SM+(HATX(1,I)-RATX(I))**2
	*      +(HATY(1,I)-RATY(I))**2
	*      +(HATZ(1,I)-RATZ(I))**2
	END DO
	RMS=DSQRT(SM/IAM(1))

	RETURN
	END
