---
title: "Hoi_quy_tuyen_tinh_don"
output: pdf_document
date: "2023-02-14"
---
Đọc dữ liệu từ csv 
```{r}
data = read.csv("C:\\Users\\ADMIN\\Downloads\\Australian Institute of Sport.csv", header = TRUE)
data

```

```{r}
#c. Tìm khoảng tin cậy 90% cho các hệ số hồi quy.
confint(lm1, level = 0.9)
```

a. Viết phương trình đường thẳng hồi quy tuyến tính của BMI theo Wt.

```{r}
lm1 = lm(data$BMI ~ data$Wt)
lm1
#=> BMI = 9.906 + 0.174*Wt
```

b. Phần dư có phân bố chuẩn với giá trị trung bình bằng 0 không?

```{r}
# LẤY RA TẬP CÁC SAI SỐ (PHẦN DƯ) TỪ MODEL lm1
e = residuals(lm1)

## BT1: 
#     H0: e tuân theo pp chuẩn
#     H1: e ko tuân theo pp chuẩn
#   Dùng shakiro test để kiểm tra xem tập e có theo pp chuẩn hay không

shapiro.test(e)

# Mặc định mức ý nghĩa 5% => alpha = 0.05
# p-value = 0.0229 < alpha = 0.05 
# => Bác bỏ H0
# KL: VỚI MỨC Ý NGHĨA 5%, CÓ CỞ SỞ ĐỂ NÓI TẬP e KO TUÂN THEO PP CHUẨN

## BT2: nếu e tuân theo pp chuẩn thì kiểm định xem giá trị tb của e có bằng 0 không?
#     H0: E[e] = 0
#     H1: E[e] != 0
t.test(e, mu = 0) #mu: mean
#     => p-value = 1 > alpha = 0.05 
#     => chấp thuận H0
```

