---
title: "LOGISTIC REGRESSION"
output: html_document
date: "2023-04-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Logistic regression: Bài toán phân lớp nhị phân (0 1)
```{r}
library(ISLR)
Smarket
View(Smarket)
summary(Smarket)
pairs(Smarket)
```

corvarian: Hệ số tương quan: Sự phụ thuộc của biến này vào biến khác. (Trong khoảng -1 đến 1) 
```{r}
cor(Smarket[ , -9])
plot(Smarket$Volume)

```

```{r}

glm.fit = glm( Direction ~ Lag1 + Lag2 + Lag3 + Lag4 + Lag5 + Volume , data = Smarket , family = binomial )

glm.prob = predict(glm.fit , type = "response")
glm.prob
plot(glm.prob)

```

```{r}
glm.pred = rep("Down" , 1250)
glm.pred[glm.prob > 0.5] = "Up"
glm.pred
# glm.pred : du doan ve tang giam trong 1250 ngay
# Direction : du doan ve tang giam trong 1250 ngay

```

```{r}
confusionMatrix(Smarket)
table(glm.pred , Smarket$Direction)
# BANG TAN SO GIUA THUC TE VA DU DOAN
#glm.pred Down  Up
#    Down  145 141
#    Up    457 507

(145+507)/1250
```

```{r}
mean(glm.pred == Smarket$Direction)


train = Smarket$Year < 2005
Smarket.2005 = Smarket[Smarket$Year == 2005 , ]
Smarket.2005
dim(Smarket.2005)
```

```{r}

glm.train = glm( Direction ~ Lag1+Lag2+Lag3+Lag4+Lag5+Volume , data = Smarket , subset = train , family = binomial)
glm.test.prob = predict(glm.train , Smarket.2005,  type = "response")
glm.test.prob
```

```{r}
length(glm.test.prob)
glm.test.pred = rep("Down" , 252)
glm.test.pred[glm.test.prob > 0.5] = "Up"
length(Smarket.2005$Direction)
length(glm.test.pred)
table( glm.test.pred , Smarket.2005$Direction )
```


